# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalkulator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    
    number = '0'
    number_2 = '0'
    dzialanie = ''
    operator = [float(number), dzialanie, float(number_2)]

    def cleen_label(self):
          Ui_Dialog.number = '0'
          Ui_Dialog.number_2 = '0'
          Ui_Dialog.dzialanie = ''
          Ui_Dialog.operator = [float(Ui_Dialog.number), Ui_Dialog.dzialanie, float(Ui_Dialog.number_2)]
          self.label.setText(Ui_Dialog.number)

    def add_number(self, add):
        if Ui_Dialog.operator[1] == '':
                if len(Ui_Dialog.number) < 12:
                        if Ui_Dialog.number[0] == '0':
                                Ui_Dialog.number = add
                        else:
                                Ui_Dialog.number = Ui_Dialog.number + add
                        self.label.setText(Ui_Dialog.number)
                        Ui_Dialog.operator[0] = float(Ui_Dialog.number)
        else:
                if len(Ui_Dialog.number) < 12:
                        if Ui_Dialog.number_2[0] == '0':
                                Ui_Dialog.number_2 = add
                        else:
                                Ui_Dialog.number_2 = Ui_Dialog.number_2 + add
                        self.label.setText(Ui_Dialog.number_2)
                        Ui_Dialog.operator[2] = float(Ui_Dialog.number_2)
              
        print(add, Ui_Dialog.operator)

    def add_dzialanie(self, add):
        Ui_Dialog.operator[1] = add
        print(Ui_Dialog.operator)
             

    def setupUi(self, Dialog):

        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(240, 384)
        Dialog.setMinimumSize(QtCore.QSize(240, 384))
        Dialog.setMaximumSize(QtCore.QSize(240, 384))
        Dialog.setStyleSheet("background-color: \'#202020\';")

        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 385))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")

        #wyświetlanie 
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(189, 100))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 25pt \"Arial\";")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 4)
        
        #kwadrat
        self.pushButton_power = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_power.setEnabled(True)
        self.pushButton_power.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_power.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_power.setObjectName("pushButton_power")
        self.gridLayout.addWidget(self.pushButton_power, 3, 0, 1, 1)

        #dzielenie
        self.pushButton_dz = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_dz.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_dz.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_dz.setObjectName("pushButton_dz")
        self.gridLayout.addWidget(self.pushButton_dz, 3, 1, 1, 1)
        self.pushButton_dz.clicked.connect(lambda: self.add_dzialanie('/'))

        #procent
        self.pushButton_per = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_per.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_per.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_per.setObjectName("pushButton_per")
        self.gridLayout.addWidget(self.pushButton_per, 3, 2, 1, 1)

        #usuwanie
        self.pushButton_CE = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_CE.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_CE.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_CE.setObjectName("pushButton_CE")
        self.gridLayout.addWidget(self.pushButton_CE, 3, 3, 1, 1)
        self.pushButton_CE.clicked.connect(self.cleen_label)

        #1
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_1.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 4, 0, 1, 1)
        self.pushButton_1.clicked.connect(lambda: self.add_number('1'))

        #2
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 1, 1, 1)
        self.pushButton_2.clicked.connect(lambda: self.add_number('2'))

        #3
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 4, 2, 1, 1)
        self.pushButton_3.clicked.connect(lambda: self.add_number('3'))

        #mnożenie
        self.pushButton_mul = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mul.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_mul.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout.addWidget(self.pushButton_mul, 4, 3, 1, 1)
        self.pushButton_mul.clicked.connect(lambda: self.add_dzialanie('*'))

        #4
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 5, 0, 1, 1)
        self.pushButton_4.clicked.connect(lambda: self.add_number('4'))

        #5        
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 5, 1, 1, 1)
        self.pushButton_5.clicked.connect(lambda: self.add_number('5'))

        #6
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_6.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 5, 2, 1, 1)
        self.pushButton_6.clicked.connect(lambda: self.add_number('6'))

        #minus
        self.pushButton_min = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_min.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_min.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_min.setObjectName("pushButton_min")
        self.gridLayout.addWidget(self.pushButton_min, 5, 3, 1, 1)
        self.pushButton_min.clicked.connect(lambda: self.add_dzialanie('-'))

        #7
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_7.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 6, 0, 1, 1)
        self.pushButton_7.clicked.connect(lambda: self.add_number('7'))

        #8
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_8.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 6, 1, 1, 1)
        self.pushButton_8.clicked.connect(lambda: self.add_number('8'))

        #9
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_9.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 6, 2, 1, 1)
        self.pushButton_9.clicked.connect(lambda: self.add_number('9'))

        #dodawanie
        self.pushButton_sum = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sum.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_sum.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_sum.setObjectName("pushButton_sum")
        self.gridLayout.addWidget(self.pushButton_sum, 6, 3, 1, 1)
        self.pushButton_sum.clicked.connect(lambda: self.add_dzialanie('+'))

        #kropka
        self.pushButton_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_dot.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_dot.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.gridLayout.addWidget(self.pushButton_dot, 7, 0, 1, 1)
        self.pushButton_dot.clicked.connect(lambda: self.add_number('.'))

        #0
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_0.setStyleSheet("background-color: rgb(59, 59, 59);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Arial\";")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 7, 1, 1, 1)
        self.pushButton_0.clicked.connect(lambda: self.add_number('0'))

        #pierwiastek
        self.pushButton_pier = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_pier.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_pier.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 75 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_pier.setObjectName("pushButton_pier")
        self.gridLayout.addWidget(self.pushButton_pier, 7, 2, 1, 1)

        #równa się
        self.pushButton_eq = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_eq.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_eq.setStyleSheet("background-color:\'#595959\';\n"
"font: 75 12pt \"Arial\";\n"
"color: \'#ffffff\';")
        self.pushButton_eq.setObjectName("pushButton_eq")
        self.gridLayout.addWidget(self.pushButton_eq, 7, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", Ui_Dialog.number))
        self.pushButton_power.setText(_translate("Dialog", "^2"))
        self.pushButton_dz.setText(_translate("Dialog", "/"))
        self.pushButton_per.setText(_translate("Dialog", "%"))
        self.pushButton_CE.setText(_translate("Dialog", "CE"))
        self.pushButton_1.setText(_translate("Dialog", "1"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_mul.setText(_translate("Dialog", "*"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_min.setText(_translate("Dialog", "-"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_8.setText(_translate("Dialog", "8")) 
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_sum.setText(_translate("Dialog", "+"))
        self.pushButton_dot.setText(_translate("Dialog", "."))
        self.pushButton_0.setText(_translate("Dialog", "0"))
        self.pushButton_pier.setText(_translate("Dialog", "_/"))
        self.pushButton_eq.setText(_translate("Dialog", "="))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
